services:
  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=payments
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  payments:
    image: landrzejewski/payments
    restart: on-failure
    ports:
      - "8080:8000"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/payments
