apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv1
  namespace: training
spec:
  capacity:
    storage: 1G
  accessModes:
    - ReadWriteMany
  #local:\
  hostPath:
    path: /tmp/pv1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv2
  namespace: training
spec:
  capacity:
    storage: 1G
  accessModes:
    - ReadWriteMany
  #local:\
  hostPath:
    path: /tmp/pv2
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv3
  namespace: training
spec:
  capacity:
    storage: 1G
  accessModes:
    - ReadWriteMany
  #local:\
  hostPath:
    path: /tmp/pv3
