apiVersion: v1
kind: Pod
metadata:
  namespace: training
  name: updater-pod
spec:
  containers:
    - name: updater
      image: landrzejewski/updater:v2
      #args:
      #  - '10'

#      env:
#        - name: INTERVAL
#          #value: '10'
#          valueFrom:
#            configMapKeyRef:
#              name: updater-config-map
#              key: INTERVAL

      envFrom:
        - configMapRef:
            name: updater-config-map
