apiVersion: v1
kind: Service
metadata:
  namespace: training
  name: payments-service
spec:
  type: NodePort
  selector:
    app-name: payments
  ports:
    - port: 80
      targetPort: http
      nodePort: 30001
